# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Felmeres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azonosito', models.CharField(max_length=10, unique=True, verbose_name='Azonosító')),
                ('telSzamFutar', models.CharField(blank=True, max_length=15)),
                ('hRSZ', models.CharField(blank=True, max_length=15, verbose_name='Helyrajzi szám')),
                ('megrendeloIrszam', models.CharField(blank=True, max_length=5)),
                ('megrendeloVaros', models.CharField(blank=True, max_length=100)),
                ('megrendeloCim', models.CharField(blank=True, max_length=100)),
                ('szallitasiIrszam', models.CharField(blank=True, max_length=5)),
                ('szallitasiVaros', models.CharField(blank=True, max_length=100)),
                ('szallitasiCim', models.CharField(blank=True, max_length=100)),
                ('sMSTelSzam', models.CharField(blank=True, max_length=15)),
                ('bmPince', models.CharField(blank=True, max_length=20)),
                ('bmFsz', models.CharField(blank=True, max_length=20)),
                ('bmEmelet', models.CharField(blank=True, max_length=20)),
                ('teruletPince', models.CharField(blank=True, max_length=20)),
                ('teruletFsz', models.CharField(blank=True, max_length=20)),
                ('teruletEmelet', models.CharField(blank=True, max_length=20)),
                ('padloHoszig', models.CharField(blank=True, max_length=20)),
                ('padloFutott', models.BooleanField(default=False)),
                ('padloFutetlenPince', models.BooleanField(default=False)),
                ('padloFutetlen', models.BooleanField(default=False)),
                ('padloAnyagFa', models.BooleanField(default=False)),
                ('padloAnyagBeton', models.BooleanField(default=False)),
                ('padloAnyagAcel', models.BooleanField(default=False)),
                ('padloAnyagTegla', models.BooleanField(default=False)),
                ('fodemHoszig', models.CharField(blank=True, max_length=20)),
                ('fodemFutott', models.BooleanField(default=False)),
                ('fodemFutetlenPadlas', models.BooleanField(default=False)),
                ('fodemFutetlen', models.BooleanField(default=False)),
                ('fodemAnyagFa', models.BooleanField(default=False)),
                ('fodemAnyagBeton', models.BooleanField(default=False)),
                ('fodemAnyagAcel', models.BooleanField(default=False)),
                ('fodemAnyagTegla', models.BooleanField(default=False)),
                ('futesHelyeKivul', models.BooleanField(default=False)),
                ('futesHelyeBelul', models.BooleanField(default=False)),
                ('futes', models.CharField(blank=True, max_length=200)),
                ('melegVizHelyeKivul', models.BooleanField(default=False)),
                ('melegVizHelyeBelul', models.BooleanField(default=False)),
                ('melegViz', models.CharField(blank=True, max_length=200)),
                ('epitesEve', models.CharField(blank=True, max_length=30)),
                ('hoszig', models.CharField(blank=True, max_length=40)),
                ('fal', models.CharField(blank=True, max_length=100)),
                ('teruletTulLap', models.CharField(blank=True, max_length=20)),
                ('szK', models.CharField(blank=True, max_length=10)),
                ('a', models.CharField(blank=True, max_length=10)),
                ('v', models.CharField(blank=True, max_length=10)),
                ('u', models.CharField(blank=True, max_length=10)),
                ('nyilasZBeepites', models.CharField(blank=True, max_length=30)),
                ('nyilasZUj', models.BooleanField(default=False)),
                ('nyilasZRegi', models.BooleanField(default=False)),
                ('nyilasZ1x', models.BooleanField(default=False)),
                ('nyilasZ2x', models.BooleanField(default=False)),
                ('nyilasZ3x', models.BooleanField(default=False)),
                ('nyilasZ4x', models.BooleanField(default=False)),
                ('nyilasZFa', models.BooleanField(default=False)),
                ('nyilasZPVC', models.BooleanField(default=False)),
                ('nyilasZFem', models.BooleanField(default=False)),
                ('ajtoUveg', models.CharField(blank=True, max_length=10)),
                ('ajtoUj', models.BooleanField(default=False)),
                ('ajtoRegi', models.BooleanField(default=False)),
                ('ajto1x', models.BooleanField(default=False)),
                ('ajto2x', models.BooleanField(default=False)),
                ('ajto3x', models.BooleanField(default=False)),
                ('ajto4x', models.BooleanField(default=False)),
                ('ajtoFa', models.BooleanField(default=False)),
                ('ajtoPVC', models.BooleanField(default=False)),
                ('ajtoFem', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Iranyitoszam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irSzam', models.IntegerField()),
                ('varos', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Megrendeles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azonosito', models.CharField(max_length=10, unique=True, verbose_name='Azonosító')),
                ('megrendeloNeve', models.CharField(max_length=100, verbose_name='Megrendelő neve')),
                ('megrendeloTelSzam', models.CharField(default='', max_length=30)),
                ('ingatlanIrszam', models.IntegerField()),
                ('ingatlanVaros', models.CharField(max_length=100, verbose_name='Ingatlan város')),
                ('ingatlanCim', models.CharField(max_length=100, verbose_name='Ingatlan Cím')),
                ('felmeresNapja', models.DateField(blank=True, null=True)),
                ('felmeresIdopontja', models.TimeField(blank=True, null=True)),
                ('felmeresDija', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='felmeres',
            name='megrendeles',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='energetika.Megrendeles'),
        ),
    ]
