# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energetika', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='felmeres',
            name='a',
            field=models.CharField(default='---', max_length=10),
        ),
        migrations.AlterField(
            model_name='felmeres',
            name='ajtoUveg',
            field=models.CharField(default='---', max_length=10),
        ),
        migrations.AlterField(
            model_name='felmeres',
            name='bmEmelet',
            field=models.CharField(default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='felmeres',
            name='bmFsz',
            field=models.CharField(default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='felmeres',
            name='bmPince',
            field=models.CharField(default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='felmeres',
            name='fodemHoszig',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='felmeres',
            name='padloHoszig',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='felmeres',
            name='szK',
            field=models.CharField(default='---', max_length=10),
        ),
        migrations.AlterField(
            model_name='felmeres',
            name='teruletEmelet',
            field=models.CharField(default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='felmeres',
            name='teruletFsz',
            field=models.CharField(default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='felmeres',
            name='teruletPince',
            field=models.CharField(default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='felmeres',
            name='teruletTulLap',
            field=models.CharField(default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='felmeres',
            name='v',
            field=models.CharField(default='---', max_length=10),
        ),
    ]
