# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-25 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energetika', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='megrendeles',
            name='felmeresNapja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='megrendeles',
            name='felmeresDija',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='megrendeles',
            name='felmeresIdopontja',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='megrendeles',
            name='ingatlanIrszam',
            field=models.IntegerField(),
        ),
    ]
