# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-28 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energetika', '0002_auto_20170125_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megrendeles',
            name='azonosito',
            field=models.CharField(max_length=10, unique=True, verbose_name='Azonosító'),
        ),
    ]
