# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energetika', '0002_auto_20170221_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='felmeres',
            name='hoszig',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
