# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energetika', '0003_auto_20170221_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='felmeres',
            name='szla',
            field=models.IntegerField(default=0),
        ),
    ]
