# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energetika', '0003_auto_20170128_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megrendeles',
            name='azonosito',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Azonosító'),
        ),
    ]
