# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energetika', '0005_auto_20170206_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iranyitoszam',
            name='irSzam',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='iranyitoszam',
            name='varos',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
