# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energetika', '0006_auto_20170207_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iranyitoszam',
            name='irSzam',
            field=models.IntegerField(),
        ),
    ]
